package responses;

/**
 * HTTP response information when attempting to create a new game
 */
public class CreateGameResponse {
    /**
     * The string which will contain the response message, corresponding to the response status code
     */
    private String message;
    /**
     * The string which will contain the user-created name of the game
     */
    private String gameName;
    /**
     * The int which serves as the unique game ID, generated by incrementing a counter
     */
    private Integer gameID;
    public int getGameID() {
        return gameID;
    }
    public void setGameID(int gameID) {
        this.gameID = gameID;
    }
    public String getMessage() {
        return message;
    }
    public void setMessage(String message) {
        this.message = message;
    }
    public String getGameName() {
        return gameName;
    }
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }
}
