package responses;

/**
 * HTTP response information when attempting to join a chess game
 */
public class JoinGameResponse {
    /**
     * The string which will contain the response message, corresponding to the response status code
     */
    private String message;
    /**
     * The int which serves as the unique game ID, generated by incrementing a counter
     */
    private String gameID;
    public String getMessage() {
        return message;
    }
    public void setMessage(String message) {
        this.message = message;
    }
    public String getGameID() {
        return gameID;
    }
    public void setGameID(String gameID) {
        this.gameID = gameID;
    }
}
